<?php
  include 'header.php';
?>
<!------------ CONTENT ------------->  
    <div class="content-wrap2">
        <div class="content-center">
<h1>Terms of Service</h1>

<h2>1. Introduction & Acceptance of Terms</h2>
<p>Welcome to Project STYL. These terms and conditions (the "Terms") govern your access to and use of Project STYL's website, services, applications, and tools (collectively, the "Services"). By accessing, viewing, or using any part of our Services, you, the user ("User"), enter into a legally binding agreement with Project STYL ("Company"), the owner and operator of the Services. You affirm that you have read, understand, and agree to be bound by these Terms, as well as any future modifications. If at any point you do not agree to these terms, please discontinue the use of our Services immediately.</p>
<p>Your use of the Services is also subject to our Privacy Policy, which covers how we collect, use, share, and store your personal information. You recognize and agree that by using our Services, you have granted us the right to use your information in the manner described in our Privacy Policy. Please take the time to read it thoroughly.</p>

<h2>2. Registration & User Responsibilities</h2>
<p>To access certain features of our Services, you may be required to register an account. In the registration process, you agree to provide current, complete, and accurate information as prompted by our registration forms. You are responsible for updating this information to maintain its completeness and accuracy. The safety and security of your account hinge upon your diligence in protecting your password and other account information. You are advised to use a strong password and take reasonable measures to protect your account from unauthorized access.</p>
<p>By creating an account, you affirm that you are of legal age to enter into a binding contract, or, if you are not, you have obtained parental or guardian consent to do so. You assume all responsibility for your activities on the account and agree to notify the Company immediately of any unauthorized use or breach of security. The Company will not be liable for any acts or omissions by you, including any damages of any kind incurred as a result of such acts or omissions.</p>

<h2>3. User Content & Conduct</h2>
<p>As a User, you are solely responsible for any and all content that you upload, post, email, transmit, or otherwise make available via the Services ("User Content"). You certify that you own all intellectual property rights in your User Content or have obtained all necessary permissions to distribute it via the Services. By sharing your User Content, you grant the Company a non-exclusive, transferable, sub-licensable, royalty-free, global license to use, copy, modify, distribute, publish, and process the information and content you provide through our Services, without any further consent, notice, and/or compensation to you or others.</p>
<p>You agree to conduct yourself in a lawful and respectful manner while using the Services. You will not post or transmit content that is defamatory, obscene, threatening, invasive of privacy, infringing of intellectual property rights, or otherwise injurious or objectionable. Furthermore, you will not upload or spread any software viruses or any other computer code, files, or programs designed to interrupt, destroy, or limit the functionality of any computer software or hardware or telecommunications equipment. The Company reserves the right, but not the obligation, to monitor, edit, or remove any activity or content at its sole discretion.</p>

<h2>4. E-commerce Transactions & Disclaimers</h2>
<p>The Services may include features that allow for transactions between users, such as buying, selling, and trading items. All transactions made through the Services are between the transacting parties only. The Company is not involved in any transaction, does not handle payments or shipping, does not guarantee transactions, and is not responsible for the quality, safety, legality, or any other aspect of items offered for sale or trade. Each user acknowledges and agrees that the Company is a neutral facilitator and is not and will not be a party to any transactions.</p>
<p>It is the responsibility of each user to perform due diligence before entering into a transaction. You are responsible for reading the full item listing before making a commitment to buy or sell. By using this feature, you agree to release the Company from claims, demands, and damages arising out of or in any way connected with such disputes.</p>

<h2>5. Ethical Consumption & Brand Information</h2>
<p>The Company actively supports ethical consumption and endeavors to provide Users with information about the sourcing, manufacturing, and distribution practices of the brands featured on the platform. This information is compiled from credible sources and is presented in good faith. However, the Company cannot warrant the absolute accuracy, reliability, or completeness of this information and advises Users to engage in their own research to verify such details.</p>
<p>By using our Services, you acknowledge that the Company is not responsible for any inaccuracies in the information provided and will not be liable for any action you take based on such information. You agree to hold the Company harmless against any claims related to purchasing decisions influenced by information provided by the platform. The Company encourages Users to support brands and products that demonstrate a commitment to fair labor practices, sustainable manufacturing, and transparent business operations.</p>

<h2>6. Intellectual Property</h2>
<p>The Services and all materials therein, including without limitation, the Project STYL logo, design, text, graphics, and other files, and the selection, arrangement and organization thereof, are owned by the Company or are the property of the Company's licensors and suppliers. You agree not to modify, reproduce, perform, display, create derivative works from, republish, post, transmit, or distribute any of the Company's intellectual property from the Services without the prior written authorization of the Company.</p>
<p>Unauthorized use of any materials contained on the Services may violate copyright, trademark laws, the laws of privacy and publicity, and communications regulations and statutes. If you believe that your intellectual property rights are being infringed upon by our Services, please notify us by sending an in-depth claim to the designated agent of the Company, including all necessary documentation. Your claim will be reviewed, and appropriate actions will be taken to address your concerns.</p>

<h2>7. Limitation of Liability & Indemnification</h2>
<p>You understand and agree that the Company shall not be liable for any direct, indirect, incidental, special, consequential or exemplary damages, including but not limited to, damages for loss of profits, goodwill, use, data or other intangible losses (even if the Company has been advised of the possibility of such damages), resulting from the use or the inability to use the Services. The Company's total liability to you for all claims arising from or related to the Services or these Terms, whether in contract, tort, or otherwise, is limited to the amounts you have paid to the Company for access to and use of the Services.</p>
<p>You agree to indemnify, defend and hold harmless the Company, its officers, directors, employees, agents, licensors, suppliers and any third-party information providers to the Services from and against all losses, expenses, damages and costs, including reasonable attorneys' fees, resulting from any violation of these Terms by you or any other person accessing the Services using your Internet account.</p>

<h2>8. Amendments to the Terms</h2>
<p>The Company reserves the right, at its sole discretion, to change, modify, add or remove portions of these Terms, at any time. It is your responsibility to check these Terms periodically for changes. Your continued use of the Services following the posting of changes will mean that you accept and agree to the changes. As long as you comply with these Terms, the Company grants you a personal, non-exclusive, non-transferable, limited privilege to enter and use the Services.</p>
<p>Any amendment or modification to the Terms is effective immediately upon posting unless otherwise stated. Your use of the Services following the date of any such amendment or modification constitutes your agreement to be bound by the modified Terms. If you do not agree to the modified Terms, your sole and exclusive remedy is to terminate your use of the Services.</p>

<h2>9. Governing Law & Jurisdiction</h2>
<p>These Terms and your use of the Services will be governed by and construed in accordance with the laws of the jurisdiction in which the Company is established, without giving effect to any principles of conflicts of law. You agree that any action at law or in equity arising out of or relating to these Terms or the Services shall be filed only in the state and federal courts located in the Company's jurisdiction and you hereby consent and submit to the personal jurisdiction of such courts for the purposes of litigating any such action.</p>
<p>In the event that any provision of these Terms is determined to be unlawful, void or unenforceable, such provision shall nonetheless be enforceable to the fullest extent permitted by applicable law, and the unenforceable portion shall be deemed to be severed from these Terms, such determination shall not affect the validity and enforceability of any other remaining provisions.</p>

<h2>10. Miscellaneous Provisions</h2>
<p>The failure of the Company to exercise or enforce any right or provision of these Terms shall not constitute a waiver of such right or provision. The Terms constitute the entire agreement between you and the Company and govern your use of the Services, superseding any prior agreements between you and the Company (including, but not limited to, any prior versions of the Terms).</p>
<p>If any provision of these Terms is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties' intentions as reflected in the provision, and the other provisions of the Terms remain in full force and effect.</p>

<h2>11. Dispute Resolution</h2>
<p>In the interest of resolving disputes between you and the Company in the most expedient and cost-effective manner, you and the Company agree to first attempt to negotiate any dispute informally for at least thirty (30) days before initiating any court proceeding. Negotiations will begin upon written notice from one party to the other. You and the Company agree that this dispute resolution procedure is a condition precedent that must be satisfied before initiating any litigation or filing any claim against the other party.</p>
<p>If the negotiation does not resolve the dispute, you agree that any and all disputes, claims, or controversies arising out of or relating to these Terms, the Services, or the breach, termination, enforcement, interpretation, or validity thereof, including the determination of the scope or applicability of this agreement to arbitrate, shall be determined by arbitration in the jurisdiction where the Company is established. The arbitration shall be administered by a reputable arbitration association as agreed upon by the parties. The award rendered by the arbitrator shall be final and shall not be subject to appeal or review.</p>

<h2>12. Termination of Services</h2>
<p>The Company reserves the right, without notice and in its sole discretion, to terminate your license to use the Services, and to block or prevent your future access to and use of the Services if we determine that you have violated these Terms or other agreements or guidelines which may be associated with your use of the Services. Upon termination, these Terms shall terminate, but the following provisions will still apply: 2, 3, 6, 7, 11, 12, and 13.</p>
<p>Upon termination, all rights granted to you under these Terms will cease immediately, and you agree that you will immediately discontinue use of the Services. However, the Company will not be liable to you or any third party for termination of the Services or termination of your use of the Services.</p>

<h2>13. Third-Party Services and Content</h2>
<p>The Services may contain links to third-party websites or services that are not owned or controlled by the Company. The Company has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party websites or services. You further acknowledge and agree that the Company shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such content, goods or services available on or through any such websites or services.</p>
<p>We strongly advise you to read the terms and conditions and privacy policies of any third-party websites or services that you visit. The inclusion of any link does not imply endorsement by the Company of the site or any association with its operators. Certain services made available via our Services are delivered by third-party sites and organizations. By using any product, service, or functionality originating from the Services domain, you hereby acknowledge and consent that the Company may share such information and data with any third party with whom the Company has a contractual relationship to provide the requested product, service, or functionality on behalf of the Services users and customers.</p>

<h2>14. User Interactions</h2>
<p>You are solely responsible for your interactions with other users of the Services and any other parties with whom you interact through the Services. The Company reserves the right, but has no obligation, to become involved in any way with these disputes. If you have a dispute with one or more users, you release the Company (and the Company's officers, directors, agents, subsidiaries, joint ventures, and employees) from claims, demands, and damages (actual and consequential) of every kind and nature, known and unknown, arising out of or in any way connected with such disputes.</p>
<p>Furthermore, you understand that the Company cannot and does not guarantee or warrant that files available for downloading from the internet or the Services will be free of viruses or other destructive code. You are responsible for implementing sufficient procedures and checkpoints to satisfy your particular requirements for anti-virus protection and accuracy of data input and output, and for maintaining a means external to our site for any reconstruction of any lost data. The Company shall not be liable for any loss or damage caused by a distributed denial-of-service attack, viruses, or other technologically harmful material that may infect your computer equipment, computer programs, data, or other proprietary material due to your use of the Services or any services or items obtained through the Services or to your downloading of any material posted on it, or on any website linked to it.</p>

<h2>15. Advertisements</h2>
<p>Our Services may display advertisements for third-party products and services. The manner, mode, and extent of advertising by the Company on the Services are subject to change without specific notice to you. In consideration for the Company granting you access to and use of the Services, you agree that the Company may place such advertising on the Services.</p>
<p>The Company is not responsible for any loss or damage of any kind you claim to have suffered as a result of advertisements or any subsequent dealings with third-party advertisers found on or through the Services. Any questions, complaints, or claims related to any product or service advertised should be directed to the appropriate vendor.</p>

<h2>16. Service Modifications</h2>
<p>The Company reserves the right at any time to modify or discontinue, temporarily or permanently, the Services (or any part thereof) with or without notice. You agree that the Company will not be liable to you or to any third party for any modification, suspension, or discontinuance of the Services.</p>
<p>Occasionally there may be information on our Services that contains typographical errors, inaccuracies, or omissions that may relate to product descriptions, pricing, promotions, offers, and availability. The Company reserves the right to correct any errors, inaccuracies, or omissions, and to change or update information or cancel orders if any information on the Services is inaccurate at any time without prior notice (including after you have submitted your order).</p>


      </div>
    </div>
<?php
  include 'footer.php';
?>
